

services:
  # 1. Database Service
  postgres-db:
    image: postgres:15-alpine
    container_name: coopcredit-db
    environment:
      POSTGRES_DB: coopcredit_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d coopcredit_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Risk Central Mock Service
  risk-service:
    build:
      context: ./risk-central-mock-service # Ajusta esta ruta a tu carpeta del mock
      dockerfile: Dockerfile
    container_name: risk-mock
    ports:
      - "8081:8081"
    networks:
      - coop-network

  # 3. Credit Application Service (Core)
  credit-service:
    build:
      context: ./credit-application-service # Ajusta esta ruta a tu carpeta principal
      dockerfile: Dockerfile
    container_name: credit-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/coopcredit_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpassword
      EXTERNAL_RISK_SERVICE_URL: http://risk-service:8081 # Comunicaci√≥n interna Docker
    depends_on:
      postgres-db:
        condition: service_healthy
      risk-service:
        condition: service_started
    networks:
      - coop-network

networks:
  coop-network:
    driver: bridge

volumes:
  postgres_data: